package model;



import java.text.DecimalFormat;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

	@Entity
	@Table(name="artwork")

public class ArtWorkItem {
		
		
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name="ID")
	private int ID;
	@Column(name="TITLE")
	private String artworkTitle;
	@Column(name="ARTIST_NAME")
	private String artworkArtist;
	@Column(name="MEDIA")
	private String artworkMedia;
	@Column(name="YEAR")
	private String artworkYear;
	@Column(name="VALUE")
	private double artworkValue;
	
	// Default no-arg constructor
	public ArtWorkItem() {
		super();
		// TODO Auto-generated constructor stub
	}

	// Constructor for all variables except ID number which is autogenerated in the database
	public ArtWorkItem(String artworkTitle, String artworkArtist, String artworkMedia, String artworkYear,
			double artworkValue) {
		super();
		this.artworkTitle = artworkTitle;
		this.artworkArtist = artworkArtist;
		this.artworkMedia = artworkMedia;
		this.artworkYear = artworkYear;
		this.artworkValue = artworkValue;
	}

	// Constructor requiring artwork title and artist name as these are NOT NULL for database	
	public ArtWorkItem(String artworkTitle, String artworkArtist) {
		super();
		this.artworkTitle = artworkTitle;
		this.artworkArtist = artworkArtist;
	}

	// Getters and Setters
	public int getID() {
		return ID;
	}

	public void setID(int iD) {
		ID = iD;
	}

	public String getArtworkTitle() {
		return artworkTitle;
	}

	public void setArtworkTitle(String artworkTitle) {
		this.artworkTitle = artworkTitle;
	}

	public String getArtworkArtist() {
		return artworkArtist;
	}

	public void setArtworkArtist(String artworkArtist) {
		this.artworkArtist = artworkArtist;
	}

	public String getArtworkMedia() {
		return artworkMedia;
	}

	public void setArtworkMedia(String artworkMedia) {
		this.artworkMedia = artworkMedia;
	}

	public String getArtworkYear() {
		return artworkYear;
	}

	public void setArtworkYear(String artworkYear) {
		this.artworkYear = artworkYear;
	}

	public double getArtworkValue() {
		return artworkValue;
	}

	public void setArtworkValue(double artworkValue) {
		this.artworkValue = artworkValue;
	}

	// toString
	@Override
	public String toString() {
		return "ArtworkItem [ID=" + ID + ", artworkTitle=" + artworkTitle + ", artworkArtist=" + artworkArtist
				+ ", artworkMedia=" + artworkMedia + ", artworkYear=" + artworkYear + ", artworkValue=" + artworkValue
				+ "]";
	}

	/** Helper method to output artwork details in a sentence format
	 * @return
	 */
	public String returnItemDetails() {
		DecimalFormat df = new DecimalFormat("$##.00");
		return artworkTitle + " created in " + artworkYear + " by " + artworkArtist + " in " + artworkMedia + " media is currently valued at " + df.format(artworkValue) + ".";
	}
	
}
